{"parks":[
          {"latitude":"42.685","longitude":"-77.95944","name":"Letchworth State Park","desc":"Letchworth State Park, renowned as the Grand Canyon of the East, is one of the most scenically magnificent areas in the eastern U.S. The Genesee River roars through the gorge over three major waterfalls between cliffs--as high as 600 feet in some places--surrounded by lush forests.","url":"https://parks.ny.gov/parks/79/details.aspx"},
          {"latitude":"43.36139","longitude":"-77.95861","name":"Hamlin Beach State Park", "desc": "Hamlin Beach State Park's clear water, sandy beaches and 264 tent and trailer campsites bring thousands of visitors to the park each year. The Yanty Creek Marsh area at the east end of the park has a mile long self-guided trail.","url":"https://parks.ny.gov/parks/20/details.aspx"},
          {"latitude":"40.734316","longitude":"-73.338525","name":"Belmont Lake State Park","desc":"Belmont Lake State Park, located in West Babylon is a 463-acre day use park bisected by Carll's Creek and Belmont Lake.","url":"https://parks.ny.gov/parks/88/details.aspx"},
          {"latitude":"42.51667","longitude":"-77.69278","name":"Stony Brook State Park","desc":"Stony Brook State Park's terrain comprises hilly woodlands, a deep gorge with rugged cliffs overlooking three waterfalls and fascinating rock formations.","url":"https://parks.ny.gov/parks/118/details.aspx"},
          {"latitude":"42.846002","longitude":"-78.861752","name":"Buffalo Harbor State Park","desc":"The newest state park in the system, Buffalo Harbor State Park is the first state park in the city of Buffalo.","url":"https://parks.ny.gov/parks/191/details.aspx"},
          {"latitude":"42.6644","longitude":"-74.8332","name":"Betty and Wilbur Davis State Park","desc":"Perched atop a hill in Southern Otsego County, Betty and Wilbur Davis State Park provides spectacular views to the south and west. Nearly two thirds of the park is blanketed by a forest of hardwoods intermixed with smaller areas of conifer plantation.","url":"https://parks.ny.gov/parks/85/details.aspx"},
          {"latitude":"43.0209","longitude":"-79.0122","name":"Big Six Mile Creek Marina","desc":"Big Six Mile Creek State Park Marina is located in a protected inlet off of the upper Niagara River. This marina provides a boat launch for boating and world class fishing access, 134 seasonal boat slips, gasoline and oil sales, ice and pump out service. Seasonal slip vacancies are filled by a lottery every year.","url":"https://parks.ny.gov/parks/50/details.aspx"},
          {"latitude":"42.5143","longitude":"-75.6921","name":"Bowman Lake State Park","desc":"Bowman Lake State Park is a remote sylvan retreat known as 'a camper's paradise.' Scenic park roads wind through evergreen and hardwood forests to shady campsites. There is a sandy lakefront for swimmers and sunbathers with several picnic areas nearby.","url":"https://parks.ny.gov/parks/76/details.aspx"},
          {"latitude":"40.78977","longitude":" -73.271894","name":"Brentwood State Park","desc":"Brentwood State Park is a 52-acre sport facility that consists of baseball fields and soccer fields.","url":"https://parks.ny.gov/parks/187/details.aspx"},
          {"latitude":"42.903130","longitude":"-78.432938","name":"Darien Lakes State Park","desc":"Darien Lakes State Park's terrain is hilly with woodlands, ravines, streams and 12-acre Harlow Lake. The park has a total of 154 campsites, 141 with electricity and 13 primitive sites without.","url":"https://parks.ny.gov/parks/144/details.aspx"},
          {"latitude":"42.601479","longitude":"-79.082619","name":"Evangola State Park","desc":"Evangola State Park's major attraction is its beautiful arc-shaped shoreline and natural sand beach on Lake Erie. Low cliffs of Angola shale line the edge of the beach.","url":"https://parks.ny.gov/parks/91/details.aspx"},
          {"latitude":"42.785576","longitude":"-74.861572","name":"Glimmerglass State Park","desc":"Glimmerglass State Park, located eight miles outside the village of Cooperstown, overlooks Otsego Lake, the 'Glimmerglass of James Fenimore Cooper's Leatherstocking Tales.","url":"https://parks.ny.gov/parks/28/details.aspx"},
          {"latitude":"44.560173","longitude":"-75.688438","name":"Jacques Cartier State Park","desc":"Jacques Cartier State Park has a sheltered bay protecting the sandy swimming beach and campers dock. The two biggest draws for the park are unlimited boating opportunities and excellent fishing.","url":"https://parks.ny.gov/parks/114/details.aspx"},
          {"latitude":"44.724983","longitude":"-73.422920","name":"Cumberland Bay State Park","desc":"Cumberland Bay State Park, on the west shore of Lake Champlain, is very popular with campers and day-users because of its large natural sand beach and picnic grounds with tables and grills. The park has a playground and playing fields.","url":"https://parks.ny.gov/parks/34/details.aspx"},
          {"latitude":"42.967038","longitude":"-78.959856","name":"Beaver Island State Park","desc":"Located at the south end of Grand Island the park boasts a wide range of outdoor activities.  Enjoy the park's 18-hole golf course, swimming and boating facilities, or trail systems.","url":"https://parks.ny.gov/parks/56/details.aspx"}
          ]}
